// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rezervasyon.API;

#nullable disable

namespace Rezervasyon.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rezervasyon.API.Entities.Tren", b =>
                {
                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Ad");

                    b.ToTable("Trenler");
                });

            modelBuilder.Entity("Rezervasyon.API.Entities.Vagon", b =>
                {
                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DoluKoltukAdet")
                        .HasColumnType("int");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("TrenAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Ad");

                    b.HasIndex("TrenAd");

                    b.ToTable("Vagonlar");
                });

            modelBuilder.Entity("Rezervasyon.API.Entities.Vagon", b =>
                {
                    b.HasOne("Rezervasyon.API.Entities.Tren", null)
                        .WithMany("Vagonlar")
                        .HasForeignKey("TrenAd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rezervasyon.API.Entities.Tren", b =>
                {
                    b.Navigation("Vagonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
